version: 2.1

orbs:
  circle-ci-orbs: go-applications/circle-ci-orbs@0.0.1

jobs:
  test:
    working_directory: ~/repo
    executor: circle-ci-orbs/default # use the default executor specified by the orb
    steps:
      - checkout
      - circle-ci-orbs/default # Use a command from the orb in a job's steps
  
