version: 2.1

orbs:
  circle-ci-orbs: go-applications/circle-ci-orbs@0.0.1

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.15.10
    steps:
      - circle-ci-orbs/default
  
